# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  config.vm.hostname = 'serene-oath-test'

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "saucy64"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  config.vm.network "public_network", :bridge => 'en0: Wi-Fi (AirPort)'

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port 80, 8080
  # config.vm.network :forwarded_port, guest: 80, host: 8080

  # Sync an additional folder to the guest VM. The first argument is
  # the folder on the host, the second is the path on the guest to mount the
  # folder
  # config.vm.synced_folder "v-data", "/vagrant_data"
end
